#生产环境的配置文件
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.0.216:3306/cosine-backend?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: wenlu@2021