server:
  port: 9339
  ssl:
    key-store: classpath:ocareer2.pfx
    key-store-password: wenlu@2021
    key-store-type: PKCS12
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://192.168.0.216:3306/cosine-backend?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: wenlu@2021
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static,file:${filepath},file:${resumeFilePath},file:${profileFilePath},file:${recordFilePath},file:${companyFilePath},file:${sendFilePath}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
mybatis:
  configuration:
    map-underscore-to-camel-case: true
baseurl: https://127.0.0.1:9339
filepath: ../cosine/image/images/cosine

resumeFilePath: ${filepath}/resume
profileFilePath: ${filepath}/profile
recordFilePath: ${filepath}/record
companyFilePath: ${filepath}/company

sendFilePath: ${filepath}/send